<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Address;
use App\Models\Order;
use App\Models\OrderItem;
use Illuminate\Support\Facades\Hash;
use Faker\Factory as Faker;

class CustomerSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create();

        for ($i = 0; $i < 10; $i++) {
            $user = User::create([
                'name' => $faker->name,
                'email' => $faker->unique()->safeEmail,
                'password' => Hash::make('password'), 
                'phone' => $faker->phoneNumber,
                'role_id' => 1, 
                'is_active' => $i % 5 !== 0, 
                'is_verified' => true,
                'bio' => 'Customer generated by Seeder.',
            ]);

            for ($j = 0; $j < rand(1, 2); $j++) {
                Address::create([
                    'user_id' => $user->id,
                    'full_name' => $user->name,
                    'phone' => $user->phone,
                    'address_line' => $faker->streetAddress,
                    'city' => $faker->city,
                    'district' => 'District ' . rand(1, 10),
                    'ward' => 'Ward ' . rand(1, 20),
                    'is_default' => $j === 0, 
                ]);
            }

            for ($k = 0; $k < rand(0, 3); $k++) {
                $total = rand(1000000, 5000000);
                
                $order = Order::create([
                    'user_id' => $user->id,
                    'fullname' => $user->name,
                    'phone' => $user->phone,
                    'email' => $user->email,
                    'address' => $faker->address,
                    'status' => $faker->randomElement(['pending', 'processing', 'shipped', 'delivered', 'cancelled']),
                    'payment_method' => $faker->randomElement(['cod', 'vnpay', 'momo']),
                    'subtotal' => $total,
                    'shipping_fee' => 30000,
                    'total_amount' => $total + 30000,
                    'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
                ]);

                for ($m = 0; $m < rand(1, 2); $m++) {
                    OrderItem::create([
                        'order_id' => $order->id,
                        'product_id' => rand(1, 5), 
                        'product_name' => 'Converse Chuck Taylor ' . $faker->word,
                        'quantity' => rand(1, 2),
                        'price' => $total / 2,
                        'size' => rand(38, 43),
                        'total' => ($total / 2) * rand(1, 2),
                    ]);
                }
            }
        }
    }
}