<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // Chuck Taylor
            [
                'name' => 'Chuck 70 Hi – Eclipse Blackout',
                'slug' => Str::slug('Chuck 70 Hi – Eclipse Blackout'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 1890000.00,
                'sale_price' => null,
                'description' => 'The classic Chuck 70 version, made from premium canvas fabric, thicker rubber sole, and enhanced cushioning for superior comfort.',
                'color' => 'Black',
                'image' => 'images/chuck_70_hightop1.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chuck 70 Hi – Bone Ivory Relic',
                'slug' => Str::slug('Chuck 70 Hi – Bone Ivory Relic'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 1990000.00,
                'sale_price' => null,
                'description' => 'A Chuck 70 version inspired by vintage style, featuring an off-white rubber sole and thick canvas for a retro look.',
                'color' => 'Ivory',
                'image' => 'images/chuck_taylor1.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chuck 70 Hi – Crimson Heat',
                'slug' => Str::slug('Chuck 70 Hi – Crimson Heat'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 1890000.00,
                'sale_price' => null,
                'description' => 'A seasonal color update for the Chuck 70 High Top featuring vibrant red canvas.',
                'color' => 'Vivid Red',
                'image' => 'images/red1.jpg',
                'is_new' => 0,
                'is_active' => 1,
                'stock' => 20,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BB Shift – Hypervolt White',
                'slug' => Str::slug('BB Shift – Hypervolt White'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 2100000.00,
                'sale_price' => null,
                'description' => 'High-performance basketball shoe, engineered for speed and quick direction changes on the court.',
                'color' => 'White',
                'image' => 'images/all_star2.jpg',
                'is_new' => 0,
                'is_active' => 1,
                'stock' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // One Star
            [
                'name' => 'Run Star Motion – Arctic Pulse',
                'slug' => Str::slug('Run Star Motion – Arctic Pulse'),
                'brand' => 'Converse',
                'category_id' => 2,
                'price' => 2550000.00,
                'sale_price' => null,
                'description' => 'Bold, unique style with an oversized black platform sole and responsive CX foam cushioning for maximum comfort.',
                'color' => 'Black',
                'image' => 'images/one_start1.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 35,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'One Star Pro – Midnight Abyss',
                'slug' => Str::slug('One Star Pro – Midnight Abyss'),
                'brand' => 'Converse',
                'category_id' => 2,
                'price' => 2200000.00,
                'sale_price' => 1800000.00,
                'description' => 'Designed for skateboarding, with durable suede and specialized cushioning for impact protection.',
                'color' => 'Brown',
                'image' => 'images/y2k_mocha.jpg',
                'is_new' => 0,
                'is_active' => 1,
                'stock' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // All Star
            [
                'name' => 'All Star Lift – Sakura Mist',
                'slug' => Str::slug('All Star Lift – Sakura Mist'),
                'brand' => 'Converse',
                'category_id' => 3,
                'price' => 1790000.00,
                'sale_price' => null,
                'description' => 'Platform shoe designed to increase height and style. Canvas upper with a unique stacked double sole.',
                'color' => 'Red Violet',
                'image' => 'images/all_star1.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 40,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'All Star Low – White Mirage',
                'slug' => Str::slug('All Star Low – White Mirage'),
                'brand' => 'Converse',
                'category_id' => 3,
                'price' => 1450000.00,
                'sale_price' => null,
                'description' => 'The world’s most iconic sneaker model, recognized for its unmistakable silhouette and cultural authenticity.',
                'color' => 'White',
                'image' => 'images/all_star_white_low.jpg',
                'is_new' => 0,
                'is_active' => 1,
                'stock' => 100,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'All Star Hi – Deep Navy Realm',
                'slug' => Str::slug('All Star Hi – Deep Navy Realm'),
                'brand' => 'Converse',
                'category_id' => 3,
                'price' => 1890000.00,
                'sale_price' => null,
                'description' => 'The classic high-top Converse sneaker in modern navy blue, perfect for any street style.',
                'color' => 'Deep Navy',
                'image' => 'images/high_top1.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Kids / Star Player
            [
                'name' => 'Star Player 76 – Urban Canvas GS',
                'slug' => Str::slug('Star Player 76 – Urban Canvas GS'),
                'brand' => 'Converse',
                'category_id' => 2, // One Star
                'price' => 1550000.00,
                'sale_price' => null,
                'description' => 'The Star Player 76 low-top version for older kids, designed with durable and comfortable canvas.',
                'color' => 'White',
                'image' => 'images/low.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 35,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Custom
            [
                'name' => 'All Star Low – Web Noir Edition',
                'slug' => Str::slug('All Star Low – Web Noir Edition'),
                'brand' => 'Custom',
                'category_id' => 3,
                'price' => 2300000.00,
                'sale_price' => null,
                'description' => 'Custom Chuck Taylor low-top in black and white, featuring a unique spider web pattern for a bold look.',
                'color' => 'Black & White',
                'image' => 'images/custom1.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'One Star Low – Checker Fade',
                'slug' => Str::slug('One Star Low – Checker Fade'),
                'brand' => 'Custom',
                'category_id' => 2,
                'price' => 2450000.00,
                'sale_price' => null,
                'description' => 'Custom low-top sneakers with bold black and white checkerboard patterns, perfect for rock or streetwear styles.',
                'color' => 'Black & White',
                'image' => 'images/custom2.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chuck Taylor Low – Heart Snowfall',
                'slug' => Str::slug('Chuck Taylor Low – Heart Snowfall'),
                'brand' => 'Custom',
                'category_id' => 1,
                'price' => 2150000.00,
                'sale_price' => null,
                'description' => 'Custom white low-top sneakers featuring a delicate embroidered heart patch. Feminine, lightweight, and versatile.',
                'color' => 'White & Pink',
                'image' => 'images/custom3.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Converse Chuck 70 Renew x A-TRAK',
                'slug' => Str::slug('Converse Chuck 70 Renew x A-TRAK'),
                'brand' => 'Custom',
                'category_id' => 1,
                'price' => 4150000.00,
                'sale_price' => null,
                'description' => 'Special edition Chuck 70 collaboration with DJ A-TRAK, featuring recycled materials and unique design elements.',
                'color' => 'White & Red',
                'image' => 'images/special-removebg.png',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Run Star Motion – Obsidian Black',
                'slug' => Str::slug('Run Star Motion – Obsidian Black'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 2550000.00,
                'sale_price' => null,
                'description' => 'Chunky platform Run Star Motion in matte black, featuring deep-groove traction and responsive CX cushioning.',
                'color' => 'Black',
                'image' => 'images/low_run_star_black.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Run Star Motion – Glacier Blue',
                'slug' => Str::slug('Run Star Motion – Glacier Blue'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 2550000.00,
                'sale_price' => null,
                'description' => 'Light blue Run Star Motion with sculpted sole design and premium canvas upper.',
                'color' => 'Light Blue',
                'image' => 'images/low_run_star_light_blue.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Run Star Motion – Midnight Navy',
                'slug' => Str::slug('Run Star Motion – Midnight Navy'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 2550000.00,
                'sale_price' => null,
                'description' => 'Navy edition of the Run Star Motion, featuring oversized tread and soft CX foam cushioning.',
                'color' => 'Dark Blue',
                'image' => 'images/low_run_star_dark_blue.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Run Star Motion – Arctic White',
                'slug' => Str::slug('Run Star Motion – Arctic White'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 2550000.00,
                'sale_price' => null,
                'description' => 'Clean white Run Star Motion built with exaggerated sole lines and all-day comfort cushioning.',
                'color' => 'White',
                'image' => 'images/low_run_star_white.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Run Star Hike – Shadow Black',
                'slug' => Str::slug('Run Star Hike – Shadow Black'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 2450000.00,
                'sale_price' => null,
                'description' => 'High-top Run Star Hike in full black with jagged traction outsole and durable canvas.',
                'color' => 'Black',
                'image' => 'images/high_run_star_black.jpg',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chuck 70 Hi – Vintage Cream',
                'slug' => Str::slug('Chuck 70 Hi – Vintage Cream'),
                'brand' => 'Converse',
                'category_id' => 1,
                'price' => 1890000.00,
                'sale_price' => null,
                'description' => 'Classic Chuck 70 with aged-cream canvas, retro foxing, and enhanced Ortholite cushioning.',
                'color' => 'Cream',
                'image' => 'images/chuck_taylor2.png',
                'is_new' => 1,
                'is_active' => 1,
                'stock' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
